### ISSUE TITLE
Problem with error events

### ISSUE THREAD

**Issue by LucaH792** [Tidone/homeassistant_eta_integration#12]
Hello,
I have a problem with the error events. I followed steps 1-5 as described, but I don't get any event info on the second screen when I click the "Press" button, and I don't know what the issue is. Everything else, like the sensors, works perfectly.

I've tried a few things already, but it just doesn't seem to work. Maybe you have an idea on how to solve the problem.

Thank you very much.

![ha](https://github.com/Tidone/homeassistant_eta_integration/assets/152872328/6c5bdc17-f83e-45b0-aa1e-a3c514bd2201)

**Comment by LucaH792** [comment]
Hi, 
so when I insert eta_webservice_error_detected under "Listen to events" and then click on "resend error msg" button in the second tab nothing happens, as you can see in the image above. When I try to send a test event, it looks the same as for you an ID is assigned, etc. However, the number of active errors remains at 0, and the latest error shows as "-". So it somehow doesn't work for me.

**Comment by Tidone** [comment]
Hi,

I think there may be a misunderstanding.

The number of active errors on the device info page is the number of error events the ETA terminal is reporting at the moment. If the terminal is not reporting any errors/warnings/messages at all, this number is 0.
Whenever the eta terminal reports a new error, the `eta_webservice_error_detected` event will be fired automatically with the new error as payload.

That button is only for testing to check if a custom automation, which listens to these events, is working. It forces a resend of all active errors, as reported by the terminal. If the terminal doesn't report any errors (that is, if the number of active errors is 0), the button doesn't do anything.
The same applies if you send a custom error event.

**Comment by LucaH792** [comment]
Hello, I reinstalled everything again and caused an error by removing the ash box without pressing the release button, and then it worked. So, thank you very much for your help.
