### ISSUE TITLE
Configuration of new sensors not possible anymore 

### ISSUE THREAD

**Issue by Supermario3012** [Tidone/homeassistant_eta_integration#16]
Dear Bernhard,
Thanks for this great integration! I installed the integration last week without any problem. Thereafter I crated an interactive dashboard that works fine since then. However since yesterday I cannot configure any new sensors. Triggering the configuration I always get the following error "Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble" ("Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"). 
The integration is running fine. The only problem is, that I am now stuck with the set of sensor values I configured so far.  
I looked at he error logs but could not find the reason for the errors. Checked the net for causes and changed browsers, restartet the integration, restartet HA, etc., but could not resolve the problem. 
Could you give me any hint how to find and resolve the problem?
Thanx in advance!
Mario

[config_entry-eta_webservices.json](https://github.com/user-attachments/files/17146006/config_entry-eta_webservices.json)

[HA_Error_log.txt](https://github.com/user-attachments/files/17146041/HA_Error_log.txt)

**Comment by Tidone** [comment]
Hi Mario,

I just tested the reconfiguration on my system, but could not reproduce the error, so at least it's not a bug introduced with the new HA version 2024.9.3.
Could you please enable debug logging and try again?

1. Restart HA if possible (to make sure the debug logs do not show old entries)
1. Go to the integration page in HA (the one where you can click the Configure button)
1. Click on `Enable debug logging`
![304117527-af637a5b-79f5-40e4-978b-7463242c42cc](https://github.com/user-attachments/assets/892358c1-d5ae-4b7c-ac51-178d601a729a)
1. Configure the integration
1. After configuration is done, click on `Disable debug logging`.
1. This will trigger a file download. Save the file and upload it here

**Comment by Supermario3012** [comment]
Hi Bernhard,
please find attached the log file as requested.
There is one other thing I have to tell you. I had a service done on the ETA unit end of last week and the service technician upgraded the SW from 3.59.6 to 3.61.0. Don't know, if that matters? Integration and interactive dashboard still work fine.

[home-assistant_eta_webservices_2024-09-26T17-39-56.006Z.log](https://github.com/user-attachments/files/17153489/home-assistant_eta_webservices_2024-09-26T17-39-56.006Z.log)

**Comment by Tidone** [comment]
Hi Mario,

Can you please open the following links in your browser? These urls are used by the integration to query the sensors of your ETA unit.
- `192.168.178.92/user/var/40/10021/0/0/12016`
- `192.168.178.92/user/var/40/10021/0/0/12014`

The first url should succeed and show you the total consumption (`Kessel > Zählerstände > Gesamtverbrauch`).
The second url should fail and either show nothing, or show an error message.

It looks like the firmware update changed or deleted one of the sensors, and when the integration tries to access it (when doing a reconfiguration), it crashes because the ETA unit does not return any useful data.

You can either delete the integration and add it again, or you can wait for me to implement a fix, which could take a week.
If you delete the integration and add it again, you may have to update your dashboards because the old sensors won't be valid any more.

**Comment by Supermario3012** [comment]
Dear Bernhard,
thanks for your help so far. I can only try your links next week Saturday, when I  am back from NY. I give you Feedback thereafter.
Kind regards Mario

Von meinem iPhone gesendet

Am 27.09.2024 um 06:52 schrieb Bernhard Petschina ***@***.***>:

﻿

Hi Mario,

Can you please open the following links in your browser? These urls are used by the integration to query the sensors of your ETA unit.

  *   192.168.178.92/user/var/40/10021/0/0/12016
  *   192.168.178.92/user/var/40/10021/0/0/12014

The first url should succeed and show you the total consumption (Kessel > Zählerstände > Gesamtverbrauch).
The second url should fail and either show nothing, or show an error message.

It looks like the firmware update changed or deleted one of the sensors, and when the integration tries to access it (when doing a reconfiguration), it crashes because the ETA unit does not return any useful data.

You can either delete the integration and add it again, or you can wait for me to implement a fix, which could take a week.
If you delete the integration and add it again, you may have to update your dashboards because the old sensors won't be valid any more.

**Comment by Supermario3012** [comment]
Hi Bernhard,
attached the xml file with the menu information (first link: 192.168.178.92:8080/user/menu). 
As you said the 2nd link worked and returned the total consumption (in my case 6885). 
The 3rd link returned an error.

Kind regards Mario
[ETA.zip](https://github.com/user-attachments/files/17269769/ETA.zip)

**Comment by MarianBe** [comment]
Same issue here after doing a firmware-update to `3.61.1`

**Comment by Tidone** [comment]
Hi Mario and Marian,

Thanks for the file. It looks like the firmware update deleted one of the endpoints (`Kessel > Zählerstände > Verbrauch seit Wartung`).
Unfortunately the integration tries to access this one to update its value when you reconfigure it. This causes the ETA terminal to return an error, which causes the reconfiguration to fail with the internal server error.

I will push an update to fix this in the next few days. In the meantime, if you really need to reconfigure the integration, you have to delete it and add it again.

**Comment by Tidone** [comment]
Hi Mario and Marian,

I just pushed an update which should fix the issue.
You can now reconfigure the integration and if one or more endpoints are not available any more (e.g. because of a firmware update), the respective sensors won't be shown in the dialog.

**Comment by Supermario3012** [comment]
Hi Bernhard,
Version 1.1.4 solved the problem. Sensors can be configured again. Attached a screenshot after configuration, that mentions that the new firmware is not providing some old endpoints.
Thanks so much for the fast response. Problem is solved and the issue can be closed.
Greetings Mario

![ETA_Problem_solved](https://github.com/user-attachments/assets/3e1c5657-3b83-436c-8bfe-d64a80462d49)
