### ISSUE TITLE
Support for "Schieber" write operation

### ISSUE THREAD

**Issue by greentux** [Tidone/homeassistant_eta_integration#2]
The user/menu in the 1.1 issue was not complete. There is an additional value "Schieber" which is an offset for the "Heizkurve-" value. So it is possible to correct the "Heizkurve" for some reasons (party etc.).
My XML for "Heizkreis":

`
<object uri="/112/10101/0/0/12241" name="Vorlauf"/>
<object uri="/112/10101/0/0/12111" name="Heizkurve">
<object uri="/112/10101/0/0/12240" name="Schieber Position"/>
<object uri="/112/10101/0/0/12104" name="Vorlauf bei -10°C"/>
<object uri="/112/10101/0/0/12103" name="Vorlauf bei +10°C"/>
<object uri="/112/10101/0/0/12107" name="Vorlauf Absenkung"/>
`
Please support "Schieber" and also for write operation. So it could be possible to have some logic to change the value.

The description is
`
<eta xmlns="http://www.eta.co.at/rest/v1" version="1.0">
<value uri="/user/var//112/10101/0/0/12240" strValue="14" unit="%" decPlaces="0" scaleFactor="10" advTextOffset="0">140</value>
</eta>
`
So it is necessary to multiply with 10 for writing and divide with 10 for reading.

**Comment by Tidone** [comment]
Hi,

Could you post your complete `user/menu` output? That would make testing a bit easier.

Reading the value should already work because the unit is `%`, which is supported by the float sensor.

There are two possible ways to implement write operations:
1. I could use a [number entity](https://developers.home-assistant.io/docs/core/entity/number/) in box mode.
The problem with this approach is that the number entity needs a min and max value, which I can't read from the ETA terminal with API 1.1, but I could set the min and max values to arbitrary small and large values to bypass this problem.
1. I could implement a custom service, which can be used in automations to write the value.
The user then has to create his own [input number](https://www.home-assistant.io/integrations/input_number/) helper, and add an automation to read the value from the helper and call the respective service of my integration.
That way the user has to supply the min and max values.

Option 1 would be less of a hassle to implement, but IMO it would be more dangerous because the user could make his heating unit inoperable (or even damage it) by setting a sensor to an invalid value.

I think option 2 is better because the user has to actively call a service to set a value, and can't involuntarily set the value in his dashboard.

What do you think?

Regardless of the option, the implementation should be ready sometimes next week.

**Comment by greentux** [comment]
I like option 1. Its not dangerous for the heater. Its only a offset from -100 to 100%. This is usally a gap from -3K to + 3 K of the "Vorlauftemperatur". So its easy.

**Comment by Tidone** [comment]
If I would only implement writing to this single endpoint, then option 1 would be better, yes.
But if I'm already implementing the write functionality, I do it for every possible sensor, and not for a single, hardcoded, one.

I will do some tests to see which option is easier and works better.

Could you please post the output of `user/menu` (on [Pastebin](https://pastebin.com/)) to make testing easier?

**Comment by greentux** [comment]
'
<eta xmlns="http://www.eta.co.at/rest/v1" version="1.0">
<menu>
<fub uri="/112/10021" name="Kessel">
<object uri="/112/10021/0/0/12010" name="Zählerstände">
<object uri="/112/10021/0/0/12153" name="Volllaststunden"/>
<object uri="/112/10021/0/0/12016" name="Gesamtverbrauch"/>
<object uri="/112/10021/0/0/12014" name="Verbrauch seit Wartung"/>
<object uri="/112/10021/0/0/12011" name="Inhalt Pelletsbehälter"/>
<object uri="/112/10021/0/0/12012" name="Verbrauch seit Entaschung"/>
<object uri="/112/10021/0/0/12013" name="Verbrauch seit Aschebox leeren"/>
</object>
<object uri="/112/10021/0/0/12000" name="Kessel">
<object uri="/112/10021/0/0/12421" name="Einstellungen"/>
<object uri="/112/10021/0/0/12180" name="Kesseldruck"/>
<object uri="/112/10021/0/0/12161" name="Kessel">
<object uri="/112/10021/0/0/12001" name="Kessel Soll"/>
<object uri="/112/10021/0/0/12317" name="Kaskade"/>
</object>
<object uri="/112/10021/0/0/12300" name="Kessel unten"/>
<object uri="/112/10021/0/0/12078" name="Vorlaufregler 1">
<object uri="/112/10021/0/11128/0" name="Umschaltventil">
<object uri="/112/10021/0/11128/2001" name="Anforderung"/>
</object>
<object uri="/112/10021/0/11121/0" name="Vorlaufmischer 1">
<object uri="/112/10021/0/11121/2120" name="Soll Temperatur"/>
<object uri="/112/10021/0/11121/2002" name="Zustand"/>
<object uri="/112/10021/0/11121/2121" name="Ist Temperatur"/>
<object uri="/112/10021/0/11121/2127" name="Position"/>
</object>
<object uri="/112/10021/0/11123/0" name="Kesselpumpe">
<object uri="/112/10021/0/11123/2001" name="Anforderung"/>
<object uri="/112/10021/0/11123/2130" name="Ausgang"/>
</object>
</object>
<object uri="/112/10021/0/0/12162" name="Abgas">
<object uri="/112/10021/0/0/13266" name="Emissionsmessung">
<object uri="/112/10021/0/0/12116" name="Art der Messung"/>
<object uri="/112/10021/0/0/13267" name="Beginn der Messung"/>
<object uri="/112/10021/0/0/13268" name="Verriegelungsdauer"/>
<object uri="/112/10021/0/0/13269" name="Jetzt starten"/>
<object uri="/112/10021/0/0/13277" name="Messung deaktivieren"/>
</object>
</object>
<object uri="/112/10021/0/0/12165" name="Abgasgebläse"/>
<object uri="/112/10021/0/0/12164" name="Restsauerstoff"/>
<object uri="/112/10021/0/0/12050" name="Entaschung">
<object uri="/112/10021/0/0/12248" name="Beginn Ruhezeit"/>
<object uri="/112/10021/0/0/12249" name="Dauer Ruhezeit"/>
<object uri="/112/10021/0/0/12012" name="Verbrauch seit Entaschung"/>
<object uri="/112/10021/0/0/12013" name="Verbrauch seit Aschebox leeren"/>
<object uri="/112/10021/0/0/12120" name="Aschebox leeren nach"/>
<object uri="/112/10021/0/0/12014" name="Verbrauch seit Wartung"/>
</object>
<object uri="/112/10021/0/0/12005" name="Pelletsbehälter">
<object uri="/112/10021/0/0/12071" name="Pelletsbehälter auffüllen"/>
<object uri="/112/10021/0/0/12011" name="Inhalt Pelletsbehälter"/>
<object uri="/112/10021/0/0/12152" name="Saugzeitpunkt"/>
<object uri="/112/10021/0/11042/0" name="Saugturbine">
<object uri="/112/10021/0/11042/2001" name="Anforderung"/>
</object>
</object>
</object>
<object uri="/112/10021/0/0/12182" name="Sonstiges">
<object uri="/112/10021/0/0/12080" name="Ein/Aus Taste"/>
<object uri="/112/10021/0/0/12112" name="Entaschentaste"/>
<object uri="/112/10021/0/0/12152" name="Saugzeitpunkt"/>
</object>
</fub>
<fub uri="/112/10111" name="Warmwasser">
<object uri="/112/10111/0/0/12129" name="Warmwasserspeicher">
<object uri="/112/10111/12130/0/0" name="Ladezeiten">
<object uri="/112/10111/12130/0/1109" name="Schaltzustand"/>
<object uri="/112/10111/12130/0/1110" name="Temperatur"/>
<object uri="/112/10111/12130/0/1081" name="Montag">
<object uri="/112/10111/12130/0/1111" name="Absenktemperatur"/>
<object uri="/112/10111/12130/0/1082" name="Zeitfenster 1"/>
<object uri="/112/10111/12130/0/1083" name="Zeitfenster 2"/>
<object uri="/112/10111/12130/0/1084" name="Zeitfenster 3"/>
</object>
<object uri="/112/10111/12130/0/1085" name="Dienstag">
<object uri="/112/10111/12130/0/1112" name="Absenktemperatur"/>
<object uri="/112/10111/12130/0/1086" name="Zeitfenster 1"/>
<object uri="/112/10111/12130/0/1087" name="Zeitfenster 2"/>
<object uri="/112/10111/12130/0/1088" name="Zeitfenster 3"/>
</object>
<object uri="/112/10111/12130/0/1089" name="Mittwoch">
<object uri="/112/10111/12130/0/1113" name="Absenktemperatur"/>
<object uri="/112/10111/12130/0/1090" name="Zeitfenster 1"/>
<object uri="/112/10111/12130/0/1091" name="Zeitfenster 2"/>
<object uri="/112/10111/12130/0/1092" name="Zeitfenster 3"/>
</object>
<object uri="/112/10111/12130/0/1093" name="Donnerstag">
<object uri="/112/10111/12130/0/1114" name="Absenktemperatur"/>
<object uri="/112/10111/12130/0/1094" name="Zeitfenster 1"/>
<object uri="/112/10111/12130/0/1095" name="Zeitfenster 2"/>
<object uri="/112/10111/12130/0/1096" name="Zeitfenster 3"/>
</object>
<object uri="/112/10111/12130/0/1097" name="Freitag">
<object uri="/112/10111/12130/0/1115" name="Absenktemperatur"/>
<object uri="/112/10111/12130/0/1098" name="Zeitfenster 1"/>
<object uri="/112/10111/12130/0/1099" name="Zeitfenster 2"/>
<object uri="/112/10111/12130/0/1100" name="Zeitfenster 3"/>
</object>
<object uri="/112/10111/12130/0/1101" name="Samstag">
<object uri="/112/10111/12130/0/1116" name="Absenktemperatur"/>
<object uri="/112/10111/12130/0/1102" name="Zeitfenster 1"/>
<object uri="/112/10111/12130/0/1103" name="Zeitfenster 2"/>
<object uri="/112/10111/12130/0/1104" name="Zeitfenster 3"/>
</object>
<object uri="/112/10111/12130/0/1105" name="Sonntag">
<object uri="/112/10111/12130/0/1117" name="Absenktemperatur"/>
<object uri="/112/10111/12130/0/1106" name="Zeitfenster 1"/>
<object uri="/112/10111/12130/0/1107" name="Zeitfenster 2"/>
<object uri="/112/10111/12130/0/1108" name="Zeitfenster 3"/>
</object>
</object>
<object uri="/112/10111/0/0/12133" name="Einschaltdifferenz"/>
<object uri="/112/10111/0/0/12132" name="Warmwasserspeicher Soll"/>
<object uri="/112/10111/0/0/12271" name="Warmwasserspeicher"/>
<object uri="/112/10111/0/0/12652" name="Solar abschöpfen"/>
</object>
<object uri="/112/10111/0/0/12182" name="Sonstiges">
<object uri="/112/10111/0/0/12134" name="Laden Taste"/>
</object>
</fub>
<fub uri="/112/10101" name="HK1">
<object uri="/112/10101/0/0/12090" name="Heizkreis">
<object uri="/112/10101/0/0/12092" name="Betrieb"/>
<object uri="/112/10101/12113/0/0" name="Heizzeiten">
<object uri="/112/10101/12113/0/1109" name="Schaltzustand"/>
<object uri="/112/10101/12113/0/1110" name="Temperatur"/>
<object uri="/112/10101/12113/0/1081" name="Montag">
<object uri="/112/10101/12113/0/1111" name="Absenktemperatur"/>
<object uri="/112/10101/12113/0/1082" name="Zeitfenster 1"/>
<object uri="/112/10101/12113/0/1083" name="Zeitfenster 2"/>
<object uri="/112/10101/12113/0/1084" name="Zeitfenster 3"/>
</object>
<object uri="/112/10101/12113/0/1085" name="Dienstag">
<object uri="/112/10101/12113/0/1112" name="Absenktemperatur"/>
<object uri="/112/10101/12113/0/1086" name="Zeitfenster 1"/>
<object uri="/112/10101/12113/0/1087" name="Zeitfenster 2"/>
<object uri="/112/10101/12113/0/1088" name="Zeitfenster 3"/>
</object>
<object uri="/112/10101/12113/0/1089" name="Mittwoch">
<object uri="/112/10101/12113/0/1113" name="Absenktemperatur"/>
<object uri="/112/10101/12113/0/1090" name="Zeitfenster 1"/>
<object uri="/112/10101/12113/0/1091" name="Zeitfenster 2"/>
<object uri="/112/10101/12113/0/1092" name="Zeitfenster 3"/>
</object>
<object uri="/112/10101/12113/0/1093" name="Donnerstag">
<object uri="/112/10101/12113/0/1114" name="Absenktemperatur"/>
<object uri="/112/10101/12113/0/1094" name="Zeitfenster 1"/>
<object uri="/112/10101/12113/0/1095" name="Zeitfenster 2"/>
<object uri="/112/10101/12113/0/1096" name="Zeitfenster 3"/>
</object>
<object uri="/112/10101/12113/0/1097" name="Freitag">
<object uri="/112/10101/12113/0/1115" name="Absenktemperatur"/>
<object uri="/112/10101/12113/0/1098" name="Zeitfenster 1"/>
<object uri="/112/10101/12113/0/1099" name="Zeitfenster 2"/>
<object uri="/112/10101/12113/0/1100" name="Zeitfenster 3"/>
</object>
<object uri="/112/10101/12113/0/1101" name="Samstag">
<object uri="/112/10101/12113/0/1116" name="Absenktemperatur"/>
<object uri="/112/10101/12113/0/1102" name="Zeitfenster 1"/>
<object uri="/112/10101/12113/0/1103" name="Zeitfenster 2"/>
<object uri="/112/10101/12113/0/1104" name="Zeitfenster 3"/>
</object>
<object uri="/112/10101/12113/0/1105" name="Sonntag">
<object uri="/112/10101/12113/0/1117" name="Absenktemperatur"/>
<object uri="/112/10101/12113/0/1106" name="Zeitfenster 1"/>
<object uri="/112/10101/12113/0/1107" name="Zeitfenster 2"/>
<object uri="/112/10101/12113/0/1108" name="Zeitfenster 3"/>
</object>
</object>
<object uri="/112/10101/0/0/12241" name="Vorlauf"/>
<object uri="/112/10101/0/0/12111" name="Heizkurve">
<object uri="/112/10101/0/0/12240" name="Schieber Position"/>
<object uri="/112/10101/0/0/12104" name="Vorlauf bei -10°C"/>
<object uri="/112/10101/0/0/12103" name="Vorlauf bei +10°C"/>
<object uri="/112/10101/0/0/12107" name="Vorlauf Absenkung"/>
</object>
<object uri="/112/10101/12095/0/0" name="Außentemperatur verzögert">
<object uri="/112/10101/12095/0/1071" name="Lag x"/>
<object uri="/112/10101/12095/0/1072" name="Lag Tf"/>
<object uri="/112/10101/12095/0/1073" name="Lag y"/>
</object>
<object uri="/112/10101/0/0/12096" name="Heizgrenze Tag"/>
<object uri="/112/10101/0/0/12097" name="Heizgrenze Nacht"/>
<object uri="/112/10101/0/0/12100" name="Freigabe Temperatur"/>
<object uri="/112/10101/0/0/12215" name="Freigabe Temperatur"/>
<object uri="/112/10101/0/0/12652" name="Solar abschöpfen"/>
</object>
<object uri="/112/10101/0/0/12182" name="Sonstiges">
<object uri="/112/10101/0/0/12125" name="Tag Taste"/>
<object uri="/112/10101/0/0/12126" name="Auto Taste"/>
<object uri="/112/10101/0/0/12230" name="Nacht Taste"/>
<object uri="/112/10101/0/0/12080" name="Ein/Aus Taste"/>
<object uri="/112/10101/0/0/12218" name="Kommen Taste"/>
<object uri="/112/10101/0/0/12231" name="Gehen Taste"/>
<object uri="/112/10101/0/0/12232" name="Urlaub Beginn"/>
<object uri="/112/10101/0/0/12239" name="Urlaub Ende"/>
</object>
</fub>
<fub uri="/112/10201" name="Lager">
<object uri="/112/10201/0/0/12058" name="Austragung"/>
<object uri="/112/10201/0/0/12015" name="Vorrat"/>
<object uri="/112/10201/0/0/12042" name="Vorrat Warngrenze"/>
</fub>
<fub uri="/112/10241" name="Sys">
<object uri="/112/10241/0/0/10990" name="Eingänge">
<object uri="/112/10241/0/0/12197" name="Außentemperatur"/>
</object>
<object uri="/112/10241/0/0/12256" name="System">
<object uri="/112/10241/0/0/12197" name="Außentemperatur"/>
</object>
</fub>
</menu>
</eta>
'

Every configuration has its own xml. I have the configuration without buffer.

**Comment by Tidone** [comment]
Hi, I just published a new version with writable sensors.
You can reconfigure the integration to add the new sensors to HA. The first time after clicking on that button will take a while because the integration will have to populate the list of writable sensors.

The writable sensors are all defined as configuration entities, and therefore won't be shown on the lovelace dashboard by default. You either have to go to the device page, or create a manual dashboard and add the sensors there.

**Comment by greentux** [comment]
works like a charme. thx.
