### ISSUE TITLE
different values for same uri

### ISSUE THREAD

**Issue by greentux** [Tidone/homeassistant_eta_integration#4]
Hi,

I want to switch the Heizkreis every evening to "Auto" mode back.

This is the uri:
```
<value uri="/user/var//112/10101/0/0/12092" strValue="Tag" unit="" decPlaces="0" scaleFactor="1" advTextOffset="2301">2301</value>
</eta>
```

You can use this readonly for the number and the string. But its also writable with number to set the Mode to "auto"
(5 = auto).
How can we do this?

regards

**Comment by Tidone** [comment]
Hi,

`advTextOffset` is 2301, so "Auto" should be 2305, not 5, right?

There are 2 possible ways (as always ;-) ):
1. I can add the unitless entities to the list of writable entities, and you can then write any value you want
    - You can then use some Jinja2 templating magic to map the values to text (e.g. 2301 is "Tag", ...)
2. I can implement a dropdown sensor with all valid values
    - I'd need a list of all possible values for that

Can you send me all valid values for that url?
2301 should be "Tag"
2305 is "Auto" (?)
Unfortunately I don't have that url on my ETA unit, so I can't get all valid values myself.

**Comment by greentux** [comment]
I prefer first one, because I have no idea to get all the valid values...
Only with trial and see. So You mean this?

**Comment by N1Dy** [comment]
> I prefer first one, because I have no idea to get all the valid values...
> 
> Only with trial and see. So You mean this?
> 
> 

Hello,

you can get the values if you enter the Uri in a internet browser maybe later I can post an example 
It is the local ip address followed by the uri address

Best regards 
ND

**Comment by Tidone** [comment]
Hi,
@greentux Yes, you would have to set a value on the ETA unit, call the url, write down the `strValue` and value iself, change the setting on the ETA unit, and repeat all steps for every possible setting.

I dug a bit deeper to see if I can extract the look-up-table from the system software update files, but I couldn't find that specific value in any of the versions i tested (2.35.18 - 3.59.3). I did find the value `2301`, but it means `Heizen` on those versions, so it looks like that url doesn't exist on those firmware versions any more?


I think the easiest option for now is to just add a checkbox to the integration settings, which the user can check to be able to add every possible sensor as a writable one.

If someone has a look-up-table of the possible values and posts it here, I can still add the dropdown sensor option in the future.

**Comment by greentux** [comment]
I use 1.35.15 :) My heater is from 2010 and no upgrade is possible without changing a lot of hardware..
Perhaps You can use the Version 1 Files?
Otherwise I can evaluate the values manual.

**Comment by greentux** [comment]
I added a script thats writes the values while changing with names. I will check some modes in the evening...

**Comment by Tidone** [comment]
No problem.
I will implement the dropdown sensor option in the future, but first I have to find a way to automatically parse the system software files so I don't have to generate the look-up-tables by hand.

I'm closing this issue for now.
