### ISSUE TITLE
missing sensor ...

### ISSUE THREAD

**Issue by Alex-github-acc** [Tidone/homeassistant_eta_integration#8]
Hello Tidone,
first I want to say "thank you" for your ETA project :-)

I want to add the temperature sensor of my oil heater unit:
<object uri="/120/10282/0/0/12361" name="Brennertemperatur">

Unfortunately I can't find it in the imported and  selectable values. 
Can you please tell me, what I'm doing wrong or how I may add it "manually"?

Kind regards, Alex

**Comment by Tidone** [comment]
Hi Alex,

Could you share the outputs of your `/user/menu` and `/user/api` endpoints?
Just open `http://<IP>:8080/user/menu` in your browser, upload the text to `https://gist.github.com`, and share the link here.
For the api endpoint I just need the line starting with `<api version=` (it should be the second to last line)

If the temperature is shown on the display of your heater unit, it should also be selectable in the HA integration, unless it is an internal value of the heater, which is not exported via the API.

**Comment by Alex-github-acc** [comment]
Thank you for your fast reply :-)

hope the attached file shows, what you have asked for ...
Btw, the temperature of the heater is shown in my display and I am able to import it to HA with the integration from nigl.

Best regards. Alex

[2024-02-01_ETA_user_menue.pdf](https://github.com/Tidone/homeassistant_eta_integration/files/14121841/2024-02-01_ETA_user_menue.pdf)

**Comment by Tidone** [comment]
There are a few temperature sensors available, which should all be available in this integration:
```
FWM -> Warmwasser -> Bereitschaftszeiten -> Temperatur
FWM -> Zirkulation -> Zirkulationszeiten -> Temperatur
FB (HK-1) -> Heizkreis -> Temperatur
HK (HK-2) -> Heizkreis -> Temperatur
Puffer -> Erzeuger Kessel/Puffer -> Ladezeiten -> Temperatur
... and so on
```

Which one do you not see in this integration?
It could be that the names are different from nigl's integration, depending on the ETA API version. For API v1.2 I'm using the names the heater unit provides, so they could be different.

Could you please also provide the diagnostics info?
For this you have to configure this integration, then go to the device page in Home Assistant, click on the 3 dots on the device info panel in the upper left corner, and click on `Download diagnostics`
![grafik](https://github.com/Tidone/homeassistant_eta_integration/assets/19607897/d6b122c4-ca54-4fcf-b862-2e2162a72b5b)

**Comment by Alex-github-acc** [comment]
Some further information ...
I use a (32-year) old oil heater unit together with my ETA control (type GM-FC 0 and EM-C 7).
**<eta version="1.0">
<api version="1.2" uri="/user/api"/>
</eta>**

The idea is to switch my loading pump off, when the water temperature in the oi heater unit is lower as the upper temperature in the heat storage tank. And vice versus. 
Therefore I use a thermal sensor from ETA in my old oil heater and have connected it in the ETA control unit.
**<object uri="/120/10282/0/0/12361" name="Brennertemperatur">** 
The values of the temp. sensor are available in the ETA system, and also in HA when I use "nigl's / homeassistant_eta_integration". 

But I can not find this value in your - more comfortable - fork... searched for it by name, value and characteristics ... nothing :-(

As I use at the moment nigl's integration I am not able to switch back to yours easily ... sorry I am a new in HA and not yet familiar with all possibilities ;-)

I would be very happy if you could help me
Best regards, Alex

**Comment by Tidone** [comment]
I don't think this is a major bug in the integration, and it should be easy to fix.
Maybe one of my "optimizations" causes this sensor to be removed from the list of available sensors.

Could you please post the output of `http://<IP>:8080/user/var/120/10282/0/0/12361` and `http://<IP>:8080/user/varinfo/120/10282/0/0/12361`?

**Comment by Alex-github-acc** [comment]
Thx for your help :-)

http://<IP>:8080/user/var/120/10282/0/0/12361:
![image](https://github.com/Tidone/homeassistant_eta_integration/assets/117162398/1cdf53e5-3c26-4f34-b6df-9dc9e701f899)

http://<IP>:8080/user/varinfo/120/10282/0/0/12361:
![image](https://github.com/Tidone/homeassistant_eta_integration/assets/117162398/ac25a4f3-cd9f-4132-b01a-9581b15fe653)

**Comment by Tidone** [comment]
Alright, I think I see the problem. The sensor has an empty unit descriptor, which causes the integration to remove it from the list of valid sensors.
I don't know why nigl's integration still shows the sensors, because I didn't change this validation much.

I will do some tests in the next few days to see if this is really the problem.

**Comment by Alex-github-acc** [comment]
This (attachment) is the state with burner "on"
[Brenner an-02.pdf](https://github.com/Tidone/homeassistant_eta_integration/files/14154321/Brenner.an-02.pdf)
[Brenner an-01.pdf](https://github.com/Tidone/homeassistant_eta_integration/files/14154322/Brenner.an-01.pdf)

Thx a lot and have a nice weekend :-)

**Comment by Alex-github-acc** [comment]
... and here a small sight in my automatisation:
![image](https://github.com/Tidone/homeassistant_eta_integration/assets/117162398/9c237971-10f2-4f8b-8d1a-0c6c2ae28c78)
![image](https://github.com/Tidone/homeassistant_eta_integration/assets/117162398/cd519b6e-9f6e-4fe3-af20-d8ea8a4ceb69)

**Comment by Tidone** [comment]
Are you sure that's the correct sensor? Both cases show a value of 0.
You can see the value yourself if you look at the output of the `/var/...` endpoint.
The number at the end, right before `</value>`, is the one which is imported to HA.

**Comment by Tidone** [comment]
I found another sensor, which should be the one from your graphs.

Could you post the output of `http://<IP>:8080/user/var/120/10281/0/11183/0` and `http://<IP>:8080/user/varinfo/120/10281/0/11183/0`?

**Comment by Alex-github-acc** [comment]
Good evening :-)

I checked the two offered possibilities ...

This one is working :
http://<IP>:8080/user/var/120/10281/0/11183/0 

May I find it in your fork?
Greetings, Alex

**Comment by Tidone** [comment]
You should be able to find it under the name `Öl Viessmann -> Eingänge -> Brennertemperatur`.

Please post the output of both urls if you don't find it.

**Comment by Alex-github-acc** [comment]
Thx :-)))

**Comment by Tidone** [comment]
Nice, I'm glad I could help!
